name: CI

on:
  push:

permissions:
  contents: write
  packages: write

env:
  DOCKER_REPO: ghcr.io/${{ github.repository_owner }}/pgpool

jobs:
  publish_docker:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        version: ['4.4.11', '4.5.6', '4.6.0']
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push images
        uses: docker/build-push-action@v6
        with:
          context: ./pgpool.docker/
          file: ./pgpool.docker/Dockerfile.pgpool
          build-args: |
            PGPOOL_VER=${{ matrix.version }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.DOCKER_REPO }}:${{ matrix.version }}
